version: "3"

services:
#  mysql:
#    image: "mysql:latest"
#    ports:
#      - 9910:3307
#    environment:
#      - MYSQL_DATABASE=TTMS
#      - MYSQL_USER=kangning
#      - MYSQL_PASSWORD=kangning
#      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  Etcd:
    image: "quay.io/coreos/etcd:v3.5.5"
    environment:
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
    ports:
      - 2379:2379
